title: Talk Data to Me
description: An exploratory blog created to help me improve my Data Science skills
author: Jess Chace
github: https://github.com/jesster413
about: Investigator | Data Scientist
disqus_shortname:
google_analytics:
avatar_url: /static/img/female-sleuth-type-3_1f575-1f3fc-200d-2640-fe0f.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:

    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jessica-chace/"

    - icon: fa-github
      link: "https://github.com/jesster413"

share:
  twitter_username:
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Reading List
      url: /reading/
    - text: Events
      url: /events/
    - text: Contact
      url: /contact/
    - text: XML Feed
      url: /feed.xml


url: "https://jesster413.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
